CLASSES-4012 Don't blow up when a published assessment has an attachment directly attached
This rarely happens, but when it does it causes archives to fail to
create with the following error:

     java.lang.ClassCastException: org.sakaiproject.tool.assessment.data.dao.assessment.PublishedAssessmentAttachment